name: Format Code

on:
  - push
  - workflow_dispatch

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download IntelliJ
        run: wget --no-verbose -O /tmp/ij.tar.gz https://download.jetbrains.com/idea/ideaIC-2022.1.tar.gz
      - name: Unzip IntelliJ
        run: tar xzf /tmp/ij.tar.gz --directory /tmp && mv /tmp/idea* /tmp/ij
      - name: Run IntelliJ Formatting
        run: /tmp/ij/bin/format.sh -r -s ./.idea/codeStyles/Project.xml -m *.java,*.xml,*.md .
      - name: Commit and Push Formatting Changes
        uses: stefanzweifel/git-auto-commit-action@v4
